name: SolverMOTD
version: '1.2.1-SNAPSHOT'
main: net.fyrxlab.solverMOTD.SolverMOTD
api-version: '1.13'
softdepend: [PlaceholderAPI, Adventure]
commands:
  smotd:
    description: Reload plugin config.
    usage: /smotd reload
    aliases: [solvermotd]
    permission: solvermotd.reload
permissions:
  solvermotd.reload:
    description: Reload config permission.
    default: op